Repository deltaDAO/mvg-portal, pull requests merged in 2022-08, with the labels that each got.

#174 Feat/remove invoice assets
  address.config.js
  src/components/organisms/AssetContent/index.tsx
  src/components/templates/Search/utils.ts
Labels: Type: Enhancement

#179 refactor: remove vp-registry references from the portal
  app.config.js
  content/pages/history.json
  content/pages/publish/profile.json
  src/@types/Verification.d.ts
  src/components/atoms/VerifiedPublisher.module.css
  src/components/atoms/VerifiedPublisher.tsx
  src/components/organisms/AssetContent/index.tsx
  src/components/pages/Profile/Header/Stats.tsx
  src/components/pages/Profile/History/PublishedList.tsx
  src/components/pages/Profile/History/Verify.module.css
  src/components/pages/Profile/History/Verify.tsx
  src/components/pages/Profile/History/VerifyForm.tsx
  src/components/pages/Profile/History/index.tsx
  src/components/pages/Profile/index.tsx
  src/hooks/useSiteMetadata.ts
  src/pages/profile/index.tsx
Labels: Type: Enhancement

#181 feat: only allow chainid of 2021000 n the portal
  src/components/molecules/WalletNetworkSwitcher.tsx
  src/components/molecules/Web3Feedback.tsx
  src/components/pages/Publish/FormActions.tsx
  src/components/templates/PageAssetDetails.tsx
  src/providers/Asset.tsx
  src/providers/Web3.tsx
Labels: Type: Enhancement

#180 refactor: remove tutorial old code
  content/pages/tutorial/AccessControl.md
  content/pages/tutorial/ConsumeData.md
  content/pages/tutorial/CtD.md
  content/pages/tutorial/DataEconomy.md
  content/pages/tutorial/DeepDive.md
  content/pages/tutorial/DistributedLedgers.md
  content/pages/tutorial/EditMetadata.md
  content/pages/tutorial/GaiaX.md
  content/pages/tutorial/GaiaXDAO.md
  content/pages/tutorial/IDAndMetadata.md
  content/pages/tutorial/Publish.md
  content/pages/tutorial/SmartContract.md
  content/pages/tutorial/SmartContract2.md
  content/pages/tutorial/Wallets.md
  content/pages/tutorial/Web3.md
  content/pages/tutorial/index.json
  src/components/molecules/AssetTeaser.tsx
  src/components/molecules/FormFields/AssetSelection.module.css
  src/components/molecules/FormFields/AssetSelection.tsx
  src/components/molecules/MetadataFeedback.tsx
  src/components/molecules/TutorialChapter.module.css
  src/components/molecules/TutorialChapter.tsx
  src/components/organisms/AssetActions/Compute/index.tsx
  src/components/organisms/AssetActions/Edit/EditComputeDataset.tsx
  src/components/organisms/AssetActions/Edit/FormEditComputeDataset.tsx
  src/components/organisms/AssetActions/Edit/index.module.css
  src/components/organisms/AssetContent/Pricing/index.tsx
  src/components/organisms/AssetContent/index.module.css
  src/components/organisms/AssetContent/index.tsx
  src/components/pages/Profile/History/ComputeJobs/Results.tsx
  src/components/pages/Publish/FormPublish.tsx
  src/components/pages/Publish/index.tsx
  src/components/pages/Tutorial/Interactives/ConnectWallet.module.css
  src/components/pages/Tutorial/Interactives/ConnectWallet.tsx
  src/components/pages/Tutorial/Interactives/ConsumeData.module.css
  src/components/pages/Tutorial/Interactives/ConsumeData.tsx
  src/components/pages/Tutorial/Interactives/EditMetadata.tsx
  src/components/pages/Tutorial/Interactives/PublishMetadata.module.css
  src/components/pages/Tutorial/Interactives/PublishMetadata.tsx
  src/components/pages/Tutorial/Interactives/ViewHistory.module.css
  src/components/pages/Tutorial/Interactives/ViewHistory.tsx
  src/components/pages/Tutorial/TableOfContentLink.tsx
  src/components/pages/Tutorial/TableOfContentLinkIcon.module.css
  src/components/pages/Tutorial/TableOfContentLinkIcon.tsx
  src/components/pages/Tutorial/TableOfContents.module.css
  src/components/pages/Tutorial/TableOfContents.tsx
  src/components/pages/Tutorial/index.module.css
  src/components/pages/Tutorial/index.tsx
  src/components/templates/PageAssetDetails.tsx
  src/pages/tutorial.tsx
Labels: Type: Enhancement

#176 feat: update publishing disclaimers
  content/pages/publish/form-dataset.json
Labels: Priority: High, Type: Enhancement

#178 feat: update algorithm publishing disclaimer
  content/pages/publish/form-algorithm.json
Labels: Priority: High, Type: Enhancement

#187 fix: display assets when account is not connected
  src/providers/Asset.tsx
Labels: Type: Bug

#189 enhancement: replace wallet address checkbox with disclaimer
  content/pages/publish/form-algorithm.json
  content/pages/publish/form-dataset.json
  src/@types/Form.d.ts
  src/@types/MetaData.d.ts
  src/components/atoms/Alert.module.css
  src/components/atoms/ButtonBuy.tsx
  src/components/atoms/Input/Disclaimer.tsx
  src/components/organisms/AssetActions/Compute/index.module.css
  src/components/organisms/AssetActions/Compute/index.tsx
  src/components/organisms/AssetActions/Consume.module.css
  src/components/organisms/AssetActions/Consume.tsx
  src/components/organisms/AssetActions/Pool/Add/index.tsx
  src/components/organisms/AssetActions/Trade/FormTrade.tsx
  src/components/organisms/AssetActions/index.tsx
  src/components/organisms/AssetContent/Pricing/index.tsx
  src/components/pages/Publish/FormActions.module.css
  src/components/pages/Publish/FormActions.tsx
  src/components/pages/Publish/FormAlgoPublish.tsx
  src/components/pages/Publish/FormPublish.tsx
  src/components/pages/Publish/index.tsx
  src/components/pages/Verify/index.tsx
  src/models/Asset.ts
  src/models/FormAlgoPublish.ts
  src/models/FormPublish.ts
  src/providers/Asset.tsx
  src/utils/metadata.ts
  tests/unit/__fixtures__/testFormData.ts
Labels: Type: Enhancement

#195 fix: change search on fields back to 'id'
  src/components/templates/Search/utils.ts
Labels: Priority: High, Type: Bug

#197 fix: change default timeout for oceanjs to 10s
  src/providers/Ocean.tsx
Labels: Priority: High, Type: Bug

#202 update contact details
  content/pages/privacy/en.md
Labels: Priority: High, Status: Do Not Merge, Type: Enhancement

#204 Fix: duplicate dates in privacy policy
  content/pages/privacy/policies.json
  src/components/molecules/PrivacyHeader.tsx
  src/hooks/usePrivacyMetadata.ts
  tests/unit/__fixtures__/privacyMetadata.json
Labels: Priority: Mid
