Repository deltaDAO/mvg-portal, pull requests merged in 2022-09, with the labels that each got.

#206 hotfix: metadata cache uri in ocean config
  src/utils/ocean.ts
Labels: Priority: Critical, Type: Bug

#207 hotfix: update default urql provider config chainId
  src/components/molecules/FormFields/FilesInput/index.tsx
  src/providers/UrqlProvider.tsx
Labels: Priority: Critical, Status: Do Not Merge, Type: Bug

#208 Enhancement: move metdatacacheuri to chains config
  chains.config.js
  src/utils/ocean.ts
Labels: Priority: Mid, Type: Enhancement

#205 enhancement: menu ux update
  content/pages/index/onboarding/steps/ready.json
  content/pages/privacy/en.md
  content/pages/privacy/policies.json
  content/site.json
  src/components/atoms/MenuDropdown.module.css
  src/components/atoms/MenuDropdown.tsx
  src/components/molecules/Menu.module.css
  src/components/molecules/Menu.tsx
  src/components/molecules/PrivacyHeader.tsx
  src/components/molecules/SearchBar.module.css
  src/components/molecules/UserPreferences/Debug.tsx
  src/components/molecules/UserPreferences/Onboarding.tsx
  src/components/molecules/Wallet/Account.module.css
  src/components/molecules/Wallet/Details.module.css
  src/components/molecules/Wallet/Details.tsx
  src/components/molecules/Wallet/index.tsx
  src/components/organisms/Footer.module.css
  src/components/organisms/Footer.tsx
  src/components/pages/Home.tsx
  src/components/pages/Home/Onboarding/Steps/Ready.module.css
  src/components/pages/Home/Onboarding/Steps/Ready.tsx
  src/hooks/usePrivacyMetadata.ts
  src/hooks/useSiteMetadata.ts
  src/providers/UserPreferences.tsx
  tests/unit/__fixtures__/privacyMetadata.json
  tests/unit/__fixtures__/useUserPreferences.ts
Labels: Type: Enhancement

#212 feat: remove ocean branding
  chains.config.js
  src/components/molecules/FormFields/FilesInput/index.tsx
  src/components/pages/Home.module.css
  src/components/pages/Home.tsx
  src/components/templates/Page.tsx
  src/providers/UrqlProvider.tsx
Labels: Type: Enhancement

#191 feat: add support to asset type "thing"
  content/assetDisclaimer.json
  content/assetDisclaimers.json
  content/pages/privacy/en.md
  src/@types/MetaData.d.ts
  src/@types/edge/DDO.d.ts
  src/components/atoms/AssetType.tsx
  src/components/atoms/Badge.module.css
  src/components/atoms/Badge.tsx
  src/components/atoms/ButtonBuy.tsx
  src/components/atoms/EdgeAssetTeaserDetails.module.css
  src/components/atoms/EdgeAssetTeaserDetails.tsx
  src/components/molecules/AssetTeaser.tsx
  src/components/molecules/Menu.module.css
  src/components/molecules/PageHeader.tsx
  src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx
  src/components/organisms/AssetActions/Compute/index.tsx
  src/components/organisms/AssetActions/Consume.tsx
  src/components/organisms/AssetActions/index.tsx
  src/components/organisms/AssetContent/EdgeDetails.module.css
  src/components/organisms/AssetContent/EdgeDetails.tsx
  src/components/organisms/AssetContent/index.tsx
  src/components/organisms/AssetList.tsx
  src/components/organisms/HomeContent.tsx
  src/components/pages/Profile/History/PublishedList.module.css
  src/components/pages/Profile/History/PublishedList.tsx
  src/components/templates/Page.tsx
  src/components/templates/PageAssetDetails.tsx
  src/components/templates/Search/Filters.module.css
  src/components/templates/Search/Filters.tsx
  src/components/templates/Search/index.module.css
  src/components/templates/Search/index.tsx
  src/components/templates/Search/sort.module.css
  src/images/edgeAssetIcon.svg
  src/models/SortAndFilters.ts
  src/models/aquarius/BaseQueryParams.ts
  src/providers/Asset.tsx
  src/utils/aquarius.ts
  src/utils/metadata.ts
Labels: Type: Feature

#213 enhancement: new footer
  content/site.json
  src/components/App.tsx
  src/components/molecules/Menu.module.css
  src/components/molecules/Wallet/Details.module.css
  src/components/molecules/Wallet/Details.tsx
  src/components/organisms/AssetContent/Bookmark.module.css
  src/components/organisms/Footer.module.css
  src/components/organisms/Footer.tsx
  src/components/organisms/Footer/Links.module.css
  src/components/organisms/Footer/Links.tsx
  src/components/organisms/Footer/index.module.css
  src/components/organisms/Footer/index.tsx
  src/hooks/useSiteMetadata.ts
  src/images/deltaDAO_Logo_small_RGB_white.svg
Labels: Type: Enhancement

#215 feat: whitelist warning
  src/components/atoms/ButtonBuy.tsx
  src/components/organisms/AssetActions/Consume.module.css
  src/components/organisms/AssetActions/Consume.tsx
  src/components/pages/Profile/History/ComputeJobs/Results.tsx
  src/components/templates/Search/Filters.module.css
  src/components/templates/Search/index.module.css
  src/providers/Asset.tsx
  src/utils/aquarius.ts
Labels: Type: Enhancement

#223 enhancement: remove price creation warning for "thing" type assets
  src/components/organisms/AssetContent/index.tsx
Labels: Type: Enhancement

#224 fix: default tab selection in profile page
  src/components/atoms/Tabs.tsx
  src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx
  src/components/pages/Profile/History/index.tsx
Labels: Type: Bug

#228 fix: button buy disabled status
  src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx
  src/providers/Web3.tsx
Labels: Type: Bug

#227 fix: ctd details modal auto closing without user input
  src/components/pages/Profile/History/ComputeJobs/index.tsx
Labels: Type: Bug

#234 enhancement: searchbar position and animation + homepage warning removal
  content/site.json
  src/components/App.module.css
  src/components/App.tsx
  src/components/molecules/PageHeader.module.css
  src/components/molecules/PageHeader.stories.tsx
  src/components/molecules/PageHeader.tsx
  src/components/molecules/SearchBar.module.css
  src/components/molecules/SearchBar.tsx
  src/components/molecules/SearchButton.tsx
  src/components/organisms/SearchForm.module.css
  src/components/organisms/SearchForm.tsx
  src/components/pages/Home.tsx
  src/components/templates/Page.tsx
  src/providers/UserPreferences.tsx
  tests/unit/__fixtures__/useUserPreferences.ts
Labels: Type: Enhancement

#226 enhancement: move edge device details and ctd datasets to asset actions section
  src/components/atoms/Tabs.tsx
  src/components/organisms/AssetActions/Edge/Details.module.css
  src/components/organisms/AssetActions/Edge/Details.tsx
  src/components/organisms/AssetActions/Edge/index.module.css
  src/components/organisms/AssetActions/Edge/index.tsx
  src/components/organisms/AssetActions/index.tsx
  src/components/organisms/AssetContent/AlgorithmDatasetsListForCompute.tsx
  src/components/organisms/AssetContent/EdgeDetails.module.css
  src/components/organisms/AssetContent/EdgeDetails.tsx
  src/components/organisms/AssetContent/index.tsx
  src/providers/Asset.tsx
  src/utils/aquarius.ts
Labels: Type: Enhancement

#235 enhancement: add moveID portal to ecosystem dropdown
  content/site.json
Labels: Type: Enhancement

#238 enhancement: update portal title
  README.md
  content/site.json
  package.json
  src/components/atoms/Seo.tsx
Labels: Type: Enhancement

#240 fix: service SD verification error handling
  src/providers/Asset.tsx
  src/utils/compute.ts
Labels: Type: Bug

#239 feat: update compliance api uri
  app.config.js
Labels: Status: Do Not Merge

#246 feat: add sd storage service
  app.config.js
  src/components/atoms/VerifiedBadge.module.css
  src/components/atoms/VerifiedBadge.tsx
  src/components/molecules/FormFields/FilesInput/index.tsx
  src/components/molecules/FormFields/ServiceSelfDescription.module.css
  src/components/molecules/FormFields/ServiceSelfDescription.tsx
  src/components/organisms/AssetContent/MetaMain.tsx
  src/components/organisms/AssetContent/index.tsx
  src/components/pages/Verify/Visualizer.tsx
  src/components/pages/Verify/index.tsx
  src/hooks/useSiteMetadata.ts
  src/providers/Asset.tsx
  src/utils/metadata.ts
Labels: Type: Feature

#248 enhancement: skip participant verification for 22.04 service SDs
  src/components/organisms/AssetContent/MetaMain.tsx
  src/utils/metadata.ts
Labels: Type: Enhancement
