Repository deltaDAO/mvg-portal, pull requests merged in 2022-03, with the labels that each got.

#57 Enhancement: adjust featured assets
  address.config.js
  src/components/pages/Home.tsx
Labels: Type: Enhancement

#76 Feature: hero banner
  content/pages/index/content.json
  src/components/pages/Home/Content.module.css
  src/components/pages/Home/Content.tsx
  src/components/pages/Home/Hero.module.css
  src/components/pages/Home/Hero.tsx
  src/components/pages/Home/index.module.css
  src/components/pages/Home/index.tsx
  src/images/data_infrastructure_transp.png
Labels: Priority: High, Type: Feature

#72 Fix: update network metadata
  src/components/molecules/UserPreferences/Networks/index.tsx
  src/hooks/useNetworkMetadata.ts
  src/utils/web3.ts
Labels: Priority: Low

#78 Enhancement: Improve wording & content
  content/pages/index/content.json
  content/site.json
  content/thirdPartyPortals.json
  src/components/App.tsx
  src/components/molecules/PortalTeaser.module.css
  src/components/pages/Home/Content.tsx
  src/components/pages/Home/index.tsx
  src/components/pages/Profile/Header/Stats.tsx
  src/components/pages/Profile/Header/index.tsx
  src/hooks/useSiteMetadata.ts
  src/images/architecture_mvg.png
  src/images/ctd_benefits.png
  src/images/ctd_mvg.png
Labels: Priority: High, Type: Enhancement

#87 Feat: remove author field
  content/pages/edit.json
  content/pages/publish/form-algorithm.json
  content/pages/publish/form-dataset.json
  src/components/organisms/AssetContent/MetaFull.tsx
  src/components/pages/Publish/FormPublish.tsx
Labels: Priority: Mid, Type: Feature

#86 Hotfix: remove author field
  content/pages/edit.json
  content/pages/publish/form-algorithm.json
  content/pages/publish/form-dataset.json
  src/components/organisms/AssetContent/MetaFull.tsx
  src/components/pages/Publish/FormPublish.tsx
Labels: Priority: Critical, Type: Enhancement

#91 Fix: edit metadata crash
  src/components/atoms/Input/InputGroup.module.css
  src/components/molecules/FormFields/URLInput/Input.tsx
Labels: Type: Bug

#92 Fix: edit metadata crash
  src/components/atoms/Input/InputGroup.module.css
  src/components/molecules/FormFields/URLInput/Input.tsx
Labels: Type: Bug

#90 Feat/remove terms
  content/pages/publish/form-algorithm.json
  content/pages/publish/form-dataset.json
  content/pages/publish/index.json
  content/price.json
  src/components/atoms/Input/InputElement.tsx
  src/components/organisms/Footer/Links.tsx
  src/components/pages/Publish/FormAlgoPublish.tsx
Labels: Type: Feature

#93 Feat: remove terms
  content/pages/publish/form-algorithm.json
  content/pages/publish/form-dataset.json
  content/pages/publish/index.json
  content/price.json
  src/components/atoms/Input/InputElement.tsx
  src/components/organisms/Footer.tsx
  src/components/pages/Publish/FormAlgoPublish.tsx
Labels: Type: Feature

#73 Fix: query for algo's compatible datasets
  src/components/organisms/AssetActions/Compute/index.tsx
  src/components/organisms/AssetContent/AlgorithmDatasetsListForCompute.tsx
  src/utils/aquarius.ts
Labels: Priority: Mid, Type: Bug
