Repository deltaDAO/mvg-portal, pull requests merged in 2022-07, with the labels that each got.

#144 Enhancement: menu dropdown
  address.config.js
  apollo.config.js
  codegen.yml
  content/site.json
  src/components/atoms/MenuDropdown.module.css
  src/components/atoms/MenuDropdown.tsx
  src/components/molecules/Menu.module.css
  src/components/molecules/Menu.tsx
  src/hooks/useSiteMetadata.ts
  src/utils/ocean.ts
Labels: Type: Enhancement

#147 enhancement: move featured assets and hide onboarding section
  src/components/pages/Home.tsx
  src/providers/Web3.tsx
Labels: Type: Enhancement

#154 feat: add verified service provider name to asset details page
  src/components/atoms/Publisher/index.module.css
  src/components/atoms/Publisher/index.tsx
  src/components/atoms/VerifiedBadge.module.css
  src/components/atoms/VerifiedBadge.tsx
  src/components/atoms/VerifiedPublisher.tsx
  src/components/molecules/FormFields/URLInput/Input.tsx
  src/components/organisms/AssetContent/MetaMain.tsx
  src/providers/Asset.tsx
  src/utils/metadata.ts
Labels: Type: Enhancement

#153 fix: onboarding hide infinite loop
  src/components/molecules/LinkOpener.tsx
  src/components/pages/Home.tsx
Labels: Type: Bug

#156 fix: correctly set provider name from raw SD
  src/utils/metadata.ts
Labels: Type: Bug

#164 fix: update compliance service uri
  app.config.js
Labels: Priority: High, Status: Do Not Merge

#167 Enhancement: Improve Loading Speed
  src/components/atoms/Loader.module.css
  src/components/atoms/Loader.tsx
  src/components/molecules/AssetTeaser.tsx
  src/components/organisms/AssetList.tsx
  src/providers/Asset.tsx
Labels: Type: Enhancement

#172 fix: asset details not showing for publisher
  src/components/organisms/AssetContent/index.tsx
Labels: Type: Bug
