Repository deltaDAO/mvg-portal, pull requests merged in 2022-02, with the labels that each got.

#55 feat: remove announcement banner
  src/components/App.tsx
  src/components/atoms/ButtonBuy.module.css
  src/components/atoms/ButtonBuy.tsx
  src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx
  src/components/organisms/AssetActions/Compute/index.tsx
  src/providers/Web3.tsx
Labels: Type: Enhancement

#56 Enhancement: remove academy section on home page and tutorial page
  content/pages/index/intro.json
  content/pages/tutorial/AccessControl.md
  content/pages/tutorial/ConsumeData.md
  content/pages/tutorial/CtD.md
  content/pages/tutorial/DataEconomy.md
  content/pages/tutorial/DeepDive.md
  content/pages/tutorial/DistributedLedgers.md
  content/pages/tutorial/EditMetadata.md
  content/pages/tutorial/GaiaX.md
  content/pages/tutorial/GaiaXDAO.md
  content/pages/tutorial/IDAndMetadata.md
  content/pages/tutorial/Publish.md
  content/pages/tutorial/SmartContract.md
  content/pages/tutorial/SmartContract2.md
  content/pages/tutorial/Wallets.md
  content/pages/tutorial/Web3.md
  content/pages/tutorial/index.json
  src/components/molecules/AssetTeaser.tsx
  src/components/molecules/FormFields/AssetSelection.module.css
  src/components/molecules/FormFields/AssetSelection.tsx
  src/components/molecules/MetadataFeedback.tsx
  src/components/molecules/TutorialChapter.module.css
  src/components/molecules/TutorialChapter.tsx
  src/components/organisms/AssetActions/Compute/index.tsx
  src/components/organisms/AssetActions/Edit/EditComputeDataset.tsx
  src/components/organisms/AssetActions/Edit/FormEditComputeDataset.tsx
  src/components/organisms/AssetActions/Edit/index.module.css
  src/components/organisms/AssetActions/Pool/index.tsx
  src/components/organisms/AssetActions/index.tsx
  src/components/organisms/AssetContent/Bookmark.tsx
  src/components/organisms/AssetContent/Pricing/index.tsx
  src/components/organisms/AssetContent/index.module.css
  src/components/organisms/AssetContent/index.tsx
  src/components/organisms/HomeIntro.module.css
  src/components/organisms/HomeIntro.tsx
  src/components/pages/Home.tsx
  src/components/pages/Publish/FormPublish.tsx
  src/components/pages/Publish/index.tsx
  src/components/pages/Tutorial/Interactives/ConnectWallet.module.css
  src/components/pages/Tutorial/Interactives/ConnectWallet.tsx
  src/components/pages/Tutorial/Interactives/ConsumeData.module.css
  src/components/pages/Tutorial/Interactives/ConsumeData.tsx
  src/components/pages/Tutorial/Interactives/EditMetadata.tsx
  src/components/pages/Tutorial/Interactives/PublishMetadata.module.css
  src/components/pages/Tutorial/Interactives/PublishMetadata.tsx
  src/components/pages/Tutorial/Interactives/ViewHistory.module.css
  src/components/pages/Tutorial/Interactives/ViewHistory.tsx
  src/components/pages/Tutorial/TableOfContentLink.tsx
  src/components/pages/Tutorial/TableOfContentLinkIcon.module.css
  src/components/pages/Tutorial/TableOfContentLinkIcon.tsx
  src/components/pages/Tutorial/TableOfContents.module.css
  src/components/pages/Tutorial/TableOfContents.tsx
  src/components/pages/Tutorial/index.module.css
  src/components/pages/Tutorial/index.tsx
  src/components/templates/PageAssetDetails.tsx
  src/pages/tutorial.tsx
Labels: Type: Enhancement

#59 Enhancement: new footer design
  content/site.json
  src/components/organisms/Footer.module.css
  src/components/organisms/Footer.tsx
  src/components/organisms/Footer/Links.module.css
  src/components/organisms/Footer/Links.tsx
  src/components/organisms/Footer/index.module.css
  src/components/organisms/Footer/index.tsx
  src/hooks/useSiteMetadata.ts
  src/images/hashtag.svg
Labels: Type: Enhancement

#60 Update en.md
  content/pages/privacy/en.md
Labels: Priority: Mid

#58 Feat: add third party portals section to home page
  content/thirdPartyPortals.json
  src/components/molecules/AssetTeaser.module.css
  src/components/molecules/PortalTeaser.module.css
  src/components/molecules/PortalTeaser.tsx
  src/components/pages/Home.module.css
  src/components/pages/Home.tsx
  src/images/safe-FBDC-logo.svg
  src/images/udl-logo.svg
Labels: Type: Feature
