Repository deltaDAO/mvg-portal, pull requests merged in 2023-09, with the labels that each got.

#413 feat: update ecosystem links
  content/site.json
Labels: Status: Do Not Merge

#423 Update gdpr.json
  content/gdpr.json
Labels: Priority: Mid, Type: Enhancement

#419 Update imprint.md
  content/pages/imprint.md
Labels: Priority: High, Type: Enhancement
